#define I2C_ADDRESS_BME280 0x76
// NO (Normally Open) NC (Normally Closed)
#define RELAY_NIGHTLIGHT_PIN D5
#define RELAY_NIGHTLIGHT_CONTACT "NC"
#define RELAY_DAYLIGHT_PIN D6
#define RELAY_DAYLIGHT_CONTACT "NC"
#define RELAY_AIRPUMP_PIN D3
#define RELAY_AIRPUMP_CONTACT "NC"
#define RELAY_FILTER_PIN D0
#define RELAY_FILTER_CONTACT "NC"
// 5 V with 4.7 kΩ pullup required (internal pullup not sufficient)
#define WATERTEMP_SENSOR_PIN D7 
#define SENSOR_INTERVALL 60000
#define HEARTBEAT_INTERVALL 512000